# Generated by Django 3.2.16 on 2023-01-02 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='pay_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='key',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 18, 13, 54, 314939)),
        ),
        migrations.AlterField(
            model_name='trns',
            name='pnr_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 18, 13, 54, 315845)),
        ),
    ]
