# Generated by Django 3.2.16 on 2023-01-06 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230102_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='key',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 9, 31, 9, 260318)),
        ),
        migrations.AlterField(
            model_name='trns',
            name='pnr_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 9, 31, 9, 261222)),
        ),
    ]
