# Generated by Django 3.2.16 on 2023-01-06 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230106_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 9, 40, 9, 512932)),
        ),
        migrations.AlterField(
            model_name='key',
            name='is_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trns',
            name='pnr_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 9, 40, 9, 513823)),
        ),
    ]
